apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-hooks-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vivekb009/argocd-hooks.git
    targetRevision: master
    path: hookimp 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
