apiVersion: batch/v1
kind: Job
metadata:
  name: postdelete-job
  annotations:
    argocd.argoproj.io/hook: PostDelete
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "echo PostDelete Hook: Cleanup after deletion"]
      restartPolicy: Never
