apiVersion: batch/v1
kind: Job
metadata:
  name: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "echo PreSync Hook: Running before deployment"]
      restartPolicy: Never
