apiVersion: batch/v1
kind: Job
metadata:
  name: syncfail-job
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "echo SyncFail Hook: Deployment failed!"]
      restartPolicy: Never
